server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.<TU_USER>
spring.datasource.password=<TU_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
