spring.application.name=citas
server.port=9091

jwt.secret=MiSuperClaveJWT_2026_segura_32_caracteres_minimo!!
jwt.expiration=3600000

# --- CONEXIÓN A POSTGRES LOCAL ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/db_springboot
spring.datasource.url=jdbc:postgresql://localhost:5432/security_basico
spring.datasource.username=postgres
spring.datasource.password=Diris.2027ws

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
