spring.application.name=citas
server.port=9091

# --- SUPABASE SESSION POOLER (IPv4) ---
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zozxldlkpzvggxdwcnyn
spring.datasource.password=Diris.2029ws
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
